import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../app/globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps }) {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Component {...pageProps} />
    </main>
  );
}

export default MyApp;
