name: Check branch

on:
  pull_request_target: # Do not combine with explicit checkout for security reasons
    types: [opened] # Not triggering on "edited" to allow a forced path to main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: dev # Don't prevent going from development -> main
          change-to: dev
          comment: |
              Your PR was set to target `main`. PRs should be target `dev`.
              The base branch of this PR has been automatically changed to `dev`.
              If you really intend to target `main`, edit the PR.